apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::017777088392:role/codebuild-brain-build-service-role
      username: codebuild
      groups:
        - system:masters
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::017777088392:role/codebuild-brain-build-service-role\n  username: codebuild\n  groups:\n    - system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2026-04-11T23:04:45Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"533438","uid":"602630a4-f088-4894-b4e0-ff0e2fb6a07e"}}
  creationTimestamp: "2026-04-13T11:27:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "893436"
  uid: bd9abd68-36ab-478c-9b50-7621e47b31a1
