version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

  build:
    commands:
      - echo Build started
      - docker build -t brain-app .
      - docker tag brain-app saran0702/brain-app:latest

  post_build:
    commands:
      - echo Pushing image
      - docker push saran0702/brain-app:latest

      - echo Updating Kubernetes deployment
      - aws eks update-kubeconfig --region ap-south-1 --name Cluster-braintask
      - kubectl apply -f deployment.yml --validate=false
      - kubectl apply -f service.yaml --validate=false
