version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-south-1
    AWS_SDK_LOAD_CONFIG: "1"

phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

  build:
    commands:
      - echo Build started
      - docker build -t brain-app .
      - docker tag brain-app saran0702/brain-app:latest

  post_build:
    commands:
      - echo Pushing image
      - docker push saran0702/brain-app:latest

      - echo Updating Kubernetes deployment
      - aws eks update-kubeconfig --region ap-south-1 --name Cluster-braintask

      #FIX: install authenticator
      - curl -o aws-iam-authenticator https://amazon-eks.s3.ap-south-1.amazonaws.com/1.27.0/2023-11-14/bin/linux/amd64/aws-iam-authenticator
      - chmod +x aws-iam-authenticator
      - mv aws-iam-authenticator /usr/local/bin/

      - kubectl apply -f deployment.yml
      - kubectl apply -f service.yaml
